### ISSUE TITLE
Admin button doesn't show up anymore

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/course-website#39] opened 2016-08-17 08:29 UTC
I think it happened after the quiz button was added.

It works on https://01005-staging.compute.dtu.dk/ but not on https://02402-staging.compute.dtu.dk/. I can however access https://02402-staging.compute.dtu.dk/admin

**Comment by iainbryson** [comment] 2016-08-25 23:18
I can't reproduce this and there have been lots of changes so far so it's possible things have resolved inadvertently.  If it's it reproduces for you, can you save the logs?

```
docker exec -i -t dtuenote_course-website-01005_1 cat /dtu-course/app/log/production.log
```

**Comment by dtu-compute** [comment] 2016-08-29 12:40
Now the issue is a little different.

In `02402-users.yaml` am I Administrator, but I don't have access to the admin panel anymore.

**Comment by iainbryson** [comment] 2016-08-30 00:18
Aha!  This was very interesting.  The problem was that we weren't parsing the courses for 02402 (and 01006), because they weren't enabled:

```
'01005':
  name: Mathematics 1
  members: 01005-users.yaml
  groups: 01005-groups.yaml
  enabled: true
'02402':
  name: Introduction to Statistics
  members: 02402-users.yaml
  groups: 02402-groups.yaml
'01006':
  name: Mathematics 1
  members: 01006-users.yaml
  groups: 01006-groups.yaml
```

I've enabled them now and it seems to work for me. 

So I suppose we should either (1) make generate.rb smart enough to not create websites/etc for non-enabled courses and/or (2) error in the course when it's not enabled or (3) simply not worry about it.

Which would you prefer?

**Comment by dtu-compute** [comment] 2016-08-30 13:00
Interesting! =)

I am sure this sort admin/user error won't be the last, so we need to do something to catch them, so the suite doesn't start until all config files are valid.

Since https://github.com/dtu-compute/dtu-enote/blob/devel/run.sh is required to be run to start the whole thing, perhaps there could be a `validate_config.rb` script run as the very first thing, which checks all required config files for existence and have the valid fields and values?

Or what do you think?

**Comment by iainbryson** [comment] 2016-08-30 18:16
Absolutely!  That makes a lot of sense.  Other than the relevant files exist and they have non-empty values for the critical fields, what validations do you think we should have?

Is enabled: false (or missing) considered invalid?  If not, what do you want to happen when a course is not enabled?

**Comment by dtu-compute** [comment] 2016-08-31 12:47
Good point. Let me make a PoC that we can iterate one.

**Comment by iainbryson** [comment] 2016-09-02 22:36
PoC of validate_config.rb is now in.  It runs the same Gem to load the config as the Web site will (and, when I get to moving the quiz to depend on dtu-core, the quiz too).  This should ensure there are at least non-null values for all the config settings.  

It also writes out what courses are enabled and which ones aren't.

**Closed by iainbryson** 2016-09-02 22:36 UTC
Labels: need info

**Comment by dtu-compute** [comment] 2016-09-03 08:47
Very nice! =)
